spring.application.name=webtech

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://localhost:5432/webtechdb
spring.datasource.username=user
spring.datasource.password=user

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true